- name: Wait for automatic system updates to finish
  shell:  while fuser /var/lib/dpkg/lock >/dev/null 2>&1; do sleep 2; done;
  become: true
  become_method: sudo

- name: Add OpenVPN repo GPG key
  apt_key:
    id: E158C569
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
  when: openvpn_use_external_repo

- name: Add OpenVPN repo sources
  apt_repository:
    filename: openvpn
    repo: deb http://swupdate.openvpn.net/apt {{ ansible_lsb.codename }} main
  when: openvpn_use_external_repo

- name: Install requirements (Debian)
  apt: name={{item}} force=yes
  with_items: [openvpn, udev, openssl, zip]
  register: requirements_result
  until: requirements_result.cache_updated is defined
  retries: 12
  delay: 10

- name: Install dependencies (Debian)
  apt: name={{item}} force=yes
  when: openvpn_use_pam_users|default(false)
  with_items: [libpam-pwdfile, python-passlib]
  register: dependencies_result
  until: dependencies_result.cache_updated is defined
  retries: 6
  delay: 10

- name: Install easy-rsa package
  apt: name=easy-rsa
  when: openvpn_use_system_easyrsa
  register: rsa_result
  until: rsa_result.cache_updated is defined
  retries: 6
  delay: 10

- name: Install LDAP dependencies (Debian)
  apt: name=openvpn-auth-ldap force=yes
  when: openvpn_use_ldap
  register: ldap_result
  until: ldap_result.cache_updated is defined
  retries: 6
  delay: 10

- name: Install bridge dependencies (Debian)
  apt: name={{item}}
  when: openvpn_bridge
  with_items: [bridge-utils]
  register: bridge_result
  until: bridge_result.cache_updated is defined
  retries: 6
  delay: 10