- name: Configure iptables 
  iptables:
     table: nat
     chain: POSTROUTING
     out_interface: "{{ item }}"
     destination: "{{ network_cidr }}"
     jump: MASQUERADE
     state: absent
  with_items:
      - "{{ vpn_config.dev }}"

- iptables:
     chain: FORWARD
     jump: ACCEPT
     state: absent

- name: Delete the service dir for target env
  file: path="/home/DOAdmin/openvpn_{{ env_name }}" state=absent

- name: Delete supervisor configuration 
  file: path=/etc/supervisord.d/openvpn_{{ env_name }}.ini state=absent

- name: Run openvpn client via supervisor
  shell: |
    systemctl restart supervisord.service

#- name: Run openvpn client
#  shell: |
#    nohup openvpn --config /home/DOAdmin/openvpn_{{ env_name }}/{{ openvpn_clients }}.ovpn > /dev/null &

- name: Check target tun device is down 
  wait_for:  path=/sys/class/net/{{ vpn_config.dev }} state=absent

- name: Delet routing talbe
  shell: |
    route del -net "{{ network_cidr }}"
  failed_when: false
