- name: Set ip forwarding in the sysctl file and reload if necessary
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Create a service dir for target env
  file: path="/home/DOAdmin/openvpn_{{ env_name }}" state=directory 

- name: Copy target keys 
  copy: src="/tmp/{{ openvpn_clients }}.ovpn" dest="/home/DOAdmin/openvpn_{{ env_name }}"

- name: Copy supervisor configuration 
  template: 
    src: supervisor.j2 
    dest: "{{ item }}"
  with_items:
      - /etc/supervisord.d/openvpn_{{ env_name }}.ini
      - /etc/supervisor/conf.d/openvpn_{{ env_name }}.conf
  ignore_errors: true

- name: Configure routing talbe
  template: src=openvpn_rc.j2 dest="/home/DOAdmin/openvpn_{{ env_name }}/openvpn.sh" mode="0777"

- name: Run openvpn client via supervisor
  shell: "systemctl restart {{ item }}"
  with_items:
      - "supervisord.service"
      - "supervisor"
  ignore_errors: true

- name: Run openvpn client via supervisor
  shell: "supervisorctl restart {{ item }}"
  with_items:
    - "openvpn_{{ env_name }}"
    - "openvpn_{{ env_name }}_route"
    
- name: Check for tun device 
  wait_for:  path=/sys/class/net/{{ vpn_config.dev }} state=present
