---

- name: Include OS-specific variables.
  include_vars: "{{item}}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.{{ ansible_lsb.codename }}.yml"
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "Common-default.yml"
      paths: vars

- include: install.deb.yml
  when: ansible_os_family == 'Debian'

- include: install.yum.yml
  when: ansible_os_family == 'RedHat'

- include: configure.yml

- include: setup-bridge.yml

- name: Ensure OpenVPN is enabled
  shell: |
     systemctl enable openvpn
  
- name: Copy client certs to ansible host
  fetch: src="{{ openvpn_keydir }}/{{ openvpn_clients }}.ovpn"
         dest="/tmp/"
         flat=yes

- name: Configure iptables
  template: src=iptables.j2 dest=/etc/iptables_rules
  
- shell: |
    iptables-restore < /etc/iptables_rules

- name: Ensure OpenVPN is started
  shell: |
     systemctl start openvpn

- name: Ensure iptables runs on boot 
  template: 
    src: iptables-startup.j2
    dest: /etc/network/if-pre-up.d/iptables-startup
    mode: "0777"
